DB_DSN: &DB_DSN "pdo-mysql://root:password@mariadb:3306/firewall_test?serverVersion=10.6"
REDIS_CONNECTION: &REDIS_CONNECTION
  redis:
    host: redis

storage:
  type: Kanopi\Firewall\Storage\DatabaseStorage
  config:
    connection:
      dsn: *DB_DSN

block:
  Kanopi\Firewall\Plugins\IpAddress:
    priority: -100
    enable: true
    metadata:
      config:
        - "config.ip.yml"
    config: ~

  Kanopi\Firewall\Plugins\GeoLocation:
    priority: -50
    enable: true
    metadata:
      reader:
        type: reader
        db: GeoLite2-City.mmdb
    config:
      - 'country:US'
      - 'country:CA'

  Kanopi\Firewall\Plugins\Url:
    priority: -10
    enable: true
    config:
      - '!method:GET'

  Kanopi\Firewall\Plugins\VulnerabilityScore:
    priority: -75
    enable: true
    metadata:
      config:
        - "config.vulnerability-score.yml"
      default_expiration_time: 3600
      status_code: 403
      country_reader:
        type: reader
        db: GeoLite2-Country.mmdb
      asn_reader:
        type: reader
        db: GeoLite2-ASN.mmdb
    config: ~

  Kanopi\Firewall\Plugins\RateLimit:
    enable: true
    metadata:
      default_rate: 10
      default_sample: 20
      default_expiration_time: 300
      storage:
        #        type: Kanopi\Firewall\RateLimitStorage\FileRateLimitStorage
        #        config:
        #          file: /tmp/firewall.rate.data

        #        type: Kanopi\Firewall\RateLimitStorage\DatabaseRateLimitStorage
        #        config:
        #          connection:
        #            dsn: *DB_DSN

        type: Kanopi\Firewall\RateLimitStorage\RedisRateLimitStorage
        config:
          <<: *REDIS_CONNECTION

    config: ~

logger:
  # File logging
  - class: Monolog\Handler\StreamHandler
    args:
      - /var/www/html/example/data/firewall.log
      - Monolog\Level::Warning
    formatter:
      class: Monolog\Formatter\LineFormatter
      args:
        - "[%datetime%] [%level_name%] [%context.plugin%] %message% %context% %extra%\n"
        - "Y-m-d H:i:s"