DB_DSN: &DB_DSN "pdo-mysql://user:user@db:3306/default?serverVersion=10.6"
REDIS_CONNECTION: &REDIS_CONNECTION
  redis:
    host: redis

storage:
#  type: Kanopi\Firewall\Storage\FileStorage
#  config:
#    file: /tmp/firewall.data
  type: Kanopi\Firewall\Storage\DatabaseStorage
  config:
    connection:
      dsn: *DB_DSN

block:
  Kanopi\Firewall\Plugins\IpAddress:
    priority: -100
    enable: true
    config:
      - ::1
      #- 108.195.124.110
  Kanopi\Firewall\Plugins\Url:
    priority: -10
    enable: true
    config:
      - 'method:GET'
  Kanopi\Firewall\Plugins\RateLimit:
    enable: true
    metadata:
      default_rate: 10
      default_sample: 20
      default_expiration_time: 300
      storage:
        type: Kanopi\Firewall\Plugins\RateLimitStorage\FileRateLimitStorage
        config:
          file: /tmp/firewall.rate.data

#        type: Kanopi\Firewall\Plugins\RateLimitStorage\DatabaseRateLimitStorage
#        config:
#          connection:
#            dsn: *DB_DSN

#        type: Kanopi\Firewall\Plugins\RateLimitStorage\RedisRateLimitStorage
#        config:
#          <<: *REDIS_CONNECTION

    config: ~

logger:
  -
