server {
    listen 80;
    server_name localhost;

    root /var/www/html/example;
    index index.php;

    location @rewrite {
        rewrite ^/(.*)$ /index.php?$1;
    }

    location ~* ^/.well-known/ {
        allow all;
    }

    location / {
        try_files $uri /index.php?$query_string;
    }

    # Don't allow direct access to PHP files in the vendor directory.
    location ~ /vendor/.*$ {
        deny all;
        return 404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
