storage:
  type: Kanopi\Firewall\Storage\FileStorage
  config:
    file: /tmp/firewall.data

bypass: {}

block: {}

logger:
  -
    class: Monolog\Handler\StreamHandler
    args:
      - /tmp/data.log
      - Monolog\Level::Debug
    formatter:
      class: Monolog\Formatter\LineFormatter
      args:
        - "[%datetime%] [%context.plugin%] %message% %context%\n"
        - "Y-m-d\\TH:i:sP"
