<?php

declare(strict_types=1);

/*
 * This file is part of the Firewall package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Kanopi\Firewall\RateLimitStorage;

use Kanopi\Firewall\Traits\FileTrait;

/**
 * File-based rate limit storage.
 */
class FileRateLimitStorage extends InMemoryRateLimitStorage
{
    use FileTrait;

    /**
     * Location where file is stored.
     */
    protected string $filePath;

    /**
     * Constructs a new FileRateLimitStorage object.
     *
     * @param array $config
     *   Configuration array. Supported keys:
     *   - 'file' => string: Path to the JSON file holding request timestamps.
     *     Defaults to `ratelimit_data.json` inside a mode-0700, per-user
     *     fingerprinted subdirectory of the system temp directory, so
     *     counters are not readable by other users on a shared host.
     *   Any keys understood by InMemoryRateLimitStorage are also honored.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
        $this->filePath = $this->validateFilePath(
            strval($config['file'] ?? $this->defaultStoragePath('ratelimit_data.json'))
        );

        $this->getLogger()->debug('File rate limit storage initialized', [
            'file' => $this->filePath,
        ]);

        $this->loadFile();
    }

    /**
     * {@inheritdoc}
     */
    public function recordRequest(string $key, int $timestamp): void
    {
        $this->withExclusiveLock($this->filePath, function () use ($key, $timestamp): void {
            $this->loadFile();
            parent::recordRequest($key, $timestamp);

            $this->getLogger()->debug('Request recorded to file storage', [
                'key' => $key,
                'timestamp' => $timestamp,
                'file' => $this->filePath,
            ]);

            $this->saveFile();
        });
    }

    /**
     * {@inheritdoc}
     */
    public function countRequests(string $key, int $start, int $end): int
    {
        $this->loadFile();
        return parent::countRequests($key, $start, $end); // TODO: Change the autogenerated stub
    }

    /**
     * Load the file contents.
     */
    protected function loadFile(): void
    {
        $this->requests = $this->loadFromFile($this->filePath);
    }

    /**
     * Persist items to file.
     */
    protected function saveFile(): void
    {
        $this->persistToFile($this->requests, $this->filePath);
    }
}
