<?php

declare(strict_types=1);

/*
 * This file is part of the Firewall package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Kanopi\Firewall\Utility;

/**
 * Build a starting configuration from a handful of choices.
 *
 * The quick start begins with a blank YAML and a hand-written IP list, but `presets/`
 * already holds curated rule sets and the honest first config for most sites is a few lines
 * including one. This turns "read the documentation and assemble something" into answering
 * four questions (#210).
 *
 * ## It writes comments, not just keys
 *
 * The output is meant to be read and then edited, so every block says what it is for and
 * what the alternatives are. A generated file nobody understands is a file nobody will
 * change, and a firewall config that cannot be changed gets switched off.
 *
 * ## Observe mode is the default for a reason
 *
 * `mode: log` records what *would* have been blocked without blocking it. Turning on an
 * unfamiliar rule set in enforcing mode is how a deployment discovers its own false
 * positives in production, and the recovery is usually to remove the firewall rather than
 * to tune it.
 */
class StarterConfig
{
    /**
     * Presets to include for each platform.
     *
     * `malicious-requests.yml` is in every list because it is the documented starting
     * point and is platform-agnostic.
     *
     * @var array<string, array<int, string>>
     */
    private const PLATFORM_PRESETS = [
        'wordpress' => ['malicious-requests.yml', 'malicious-urls.yml', 'wordpress.yml'],
        'drupal' => ['malicious-requests.yml', 'malicious-urls.yml', 'drupal.yml'],
        'other' => ['malicious-requests.yml', 'malicious-urls.yml'],
    ];

    /**
     * What sits in front of the application, and the CIDRs to trust for it.
     *
     * The ranges are deliberately **not** listed here. Every one of these publishes its
     * own, they change, and a list baked into a generator is a list that goes stale
     * silently -- which for trusted proxies means either a spoofable firewall or a broken
     * one. The generated file points at the publisher instead.
     *
     * @var array<string, string>
     */
    private const CDN_SOURCES = [
        'cloudflare' => 'https://www.cloudflare.com/ips/',
        'pantheon' => 'https://docs.pantheon.io/guides/edge/ip-addresses',
        'wpengine' => 'https://wpengine.com/support/wordpress-ip-addresses/',
        'fastly' => 'https://api.fastly.com/public-ip-list',
    ];

    /**
     * Storage backends, and the block each writes.
     *
     * @var array<int, string>
     */
    private const STORAGE = ['file', 'database', 'redis'];

    /**
     * Every accepted value, for a caller validating input.
     *
     * @return array{platform: array<int, string>, cdn: array<int, string>, storage: array<int, string>, mode: array<int, string>}
     *   Accepted values per choice.
     */
    public static function choices(): array
    {
        return [
            'platform' => array_keys(self::PLATFORM_PRESETS),
            'cdn' => array_merge(['none'], array_keys(self::CDN_SOURCES)),
            'storage' => self::STORAGE,
            'mode' => ['log', 'block'],
        ];
    }

    /**
     * Render a starter configuration.
     *
     * @param string $platform
     *   One of `wordpress`, `drupal`, `other`.
     * @param string $cdn
     *   One of `none`, or a key of CDN_SOURCES.
     * @param string $storage
     *   One of `file`, `database`, `redis`.
     * @param string $mode
     *   `log` to observe, `block` to enforce.
     *
     * @return string
     *   YAML, commented.
     */
    public static function render(string $platform, string $cdn, string $storage, string $mode): string
    {
        $presets = self::PLATFORM_PRESETS[$platform] ?? self::PLATFORM_PRESETS['other'];

        $lines = [];
        $lines[] = '# Firewall configuration, generated by bin/firewall-init.';
        $lines[] = '#';
        $lines[] = '# Everything here is meant to be edited. The comments say what each block';
        $lines[] = '# does and what the alternatives are, so start by reading it rather than';
        $lines[] = '# by trusting it.';
        $lines[] = '';
        $lines[] = '# Rule sets shipped with the library. `{presets_dir}` resolves to this';
        $lines[] = "# package's own presets directory, wherever vendor/ happens to be.";
        $lines[] = '#';
        $lines[] = '# See docs/presets/available.md for what each one blocks.';
        $lines[] = 'configs:';

        foreach ($presets as $preset) {
            $lines[] = sprintf('  - "{presets_dir}/%s"', $preset);
        }

        $lines[] = '';
        $lines[] = 'global:';

        foreach (self::modeBlock($mode) as $line) {
            $lines[] = $line;
        }

        foreach (self::proxyBlock($cdn) as $line) {
            $lines[] = $line;
        }

        $lines[] = '';

        foreach (self::storageBlock($storage) as $line) {
            $lines[] = $line;
        }

        $lines[] = '';
        $lines[] = '# Your own rules go here, and run alongside the presets above.';
        $lines[] = '#';
        $lines[] = '# An allow rule with a negative weight is consulted before any block rule,';
        $lines[] = '# which is how you keep your office or a monitoring vendor out of trouble.';
        $lines[] = '#';
        $lines[] = '# plugins:';
        $lines[] = '#   - plugin: "Kanopi\\\\Firewall\\\\Plugins\\\\IpAddress"';
        $lines[] = '#     response: allow';
        $lines[] = '#     weight: -100';
        $lines[] = '#     enable: true';
        $lines[] = '#     metadata:';
        $lines[] = '#       name: office-network';
        $lines[] = '#     config:';
        $lines[] = '#       - "198.51.100.0/24"';

        return implode("\n", $lines) . "\n";
    }

    /**
     * The lines describing what the firewall does when a rule matches.
     *
     * @param string $mode
     *   `log` or `block`.
     *
     * @return array<int, string>
     *   YAML lines.
     */
    private static function modeBlock(string $mode): array
    {
        if ($mode === 'block') {
            return [
                '  # Enforcing. A matching request is refused.',
                '  #',
                '  # If you have not yet watched what these rules match on your own traffic,',
                '  # `mode: log` records the same decisions without acting on them.',
                '  mode: block',
            ];
        }

        return [
            '  # Observing, not enforcing. Every rule is evaluated and every match is',
            '  # logged, and nothing is refused.',
            '  #',
            '  # Leave it here for a week and read what would have been blocked. Turning an',
            '  # unfamiliar rule set straight on is how a site finds its false positives in',
            '  # production, and the usual recovery is to remove the firewall rather than to',
            '  # tune it.',
            '  #',
            '  # Change to `block` when the log is boring.',
            '  mode: log',
        ];
    }

    /**
     * The lines describing what sits in front of the application.
     *
     * @param string $cdn
     *   `none`, or a known CDN.
     *
     * @return array<int, string>
     *   YAML lines.
     */
    private static function proxyBlock(string $cdn): array
    {
        if ($cdn === 'none' || !isset(self::CDN_SOURCES[$cdn])) {
            return [
                '',
                '  # Nothing sits in front of this application, so the connecting address is',
                '  # the client. Set this to `true` if you put a CDN or load balancer there',
                '  # later -- an IP rule against a proxy you have not declared is a rule',
                '  # anyone can bypass with a forged X-Forwarded-For header.',
                '  behind_proxy: false',
            ];
        }

        return [
            '',
            '  # A proxy sits in front of this application, so the connecting address is the',
            '  # proxy and the client address comes from a header.',
            '  behind_proxy: true',
            '',
            '  # Set this to `true` once the ranges below are declared, and the firewall',
            '  # will refuse to start without them rather than run spoofable.',
            '  #',
            '  # It ships as `false` so this file works the moment it is written. While it',
            '  # is false and the proxies are undeclared, `behind_proxy: true` above makes',
            '  # the firewall log an error on every startup saying exactly that -- so the',
            '  # gap is loud, it just is not fatal yet.',
            '  require_trusted_proxies: false',
            '',
            sprintf('  # === %s: declare the ranges in your application bootstrap ===', $cdn),
            '  #',
            '  # This cannot live in YAML. Symfony reads trusted proxies from the Request',
            '  # class, so it has to be set in PHP before Firewall::create() runs -- a',
            '  # settings.php, a middleware, a functions.php.',
            '  #',
            '  #   use Symfony\\Component\\HttpFoundation\\Request;',
            '  #',
            '  #   Request::setTrustedProxies(',
            '  #       [/* ranges */],',
            '  #       Request::HEADER_X_FORWARDED_FOR,',
            '  #   );',
            '  #',
            sprintf('  # %s publishes its current ranges at:', ucfirst($cdn)),
            sprintf('  #   %s', self::CDN_SOURCES[$cdn]),
            '  #',
            '  # They are not written here on purpose: a list baked into a generated file',
            '  # goes stale without saying so, and a stale trusted-proxy list means either a',
            '  # spoofable firewall or a broken one.',
        ];
    }

    /**
     * The `storage:` block for the chosen backend.
     *
     * @param string $storage
     *   `file`, `database` or `redis`.
     *
     * @return array<int, string>
     *   YAML lines.
     */
    private static function storageBlock(string $storage): array
    {
        if ($storage === 'database') {
            return [
                '# Where blocked clients are recorded. A database is shared between servers',
                '# and survives a deploy.',
                '#',
                '# The table is created on first write. When a later release adds a column,',
                '# `bin/firewall-migrate` adds it without dropping your history.',
                '#',
                '# Set these in the environment. The defaults are placeholders so this file',
                '# loads before you have -- `bin/firewall-doctor` will tell you the database',
                '# is unreachable, which is a better first failure than a config that will',
                '# not parse.',
                'storage:',
                '  type: "Kanopi\\\\Firewall\\\\Storage\\\\DatabaseStorage"',
                '  config:',
                '    connection:',
                '      driver: "%env(default:pdo_mysql:DB_DRIVER)%"',
                '      host: "%env(default:127.0.0.1:DB_HOST)%"',
                '      port: "%env(default:3306:int:DB_PORT)%"',
                '      dbname: "%env(default:firewall:DB_NAME)%"',
                '      user: "%env(default:firewall:DB_USER)%"',
                '      password: "%env(default::DB_PASSWORD)%"',
            ];
        }

        if ($storage === 'redis') {
            return [
                '# Where blocked clients are recorded. Redis is shared between servers and',
                '# expires bans itself, so nothing has to sweep them.',
                '#',
                '# An unreachable Redis does not stop the firewall: the block list reads as',
                '# empty and every other rule keeps working. `bin/firewall-doctor` reports',
                '# when that is happening.',
                '#',
                '# Set these in the environment; the defaults are a local Redis so this file',
                '# loads before you have.',
                'storage:',
                '  type: "Kanopi\\\\Firewall\\\\Storage\\\\RedisStorage"',
                '  config:',
                '    redis:',
                '      host: "%env(default:127.0.0.1:REDIS_HOST)%"',
                '      port: "%env(default:6379:int:REDIS_PORT)%"',
                '      prefix: "firewall:"',
            ];
        }

        return [
            '# Where blocked clients are recorded. A file is the simplest thing that works',
            '# and is right for a single server.',
            '#',
            '# It is not shared: on more than one web node each keeps its own list, so a',
            '# client blocked on one is not blocked on the others. Move to `database` or',
            '# `redis` when that matters.',
            '#',
            '# The default writes to /tmp so this file works the moment it is written.',
            '# Move it somewhere durable: /tmp is cleared on reboot, and on some hosts is',
            '# per-process, which quietly gives every worker its own block list.',
            '#',
            '# Wherever it ends up must be writable by the web user and outside the',
            '# document root.',
            'storage:',
            '  type: "Kanopi\\\\Firewall\\\\Storage\\\\FileStorage"',
            '  config:',
            '    storage_file: "%env(default:/tmp/firewall-blocked.data:FIREWALL_STORAGE_FILE)%"',
        ];
    }
}
