<?php

declare(strict_types=1);

/*
 * This file is part of the Firewall package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Kanopi\Firewall\Source;

use Kanopi\Firewall\Logging\LoggingTrait;

/**
 * Stores the *result* of a source, not the bytes it came from.
 *
 * Caching a raw body only saves the download. The expensive part of a large
 * list is decoding it — a 9,000-entry JSON document parsed, selected, filtered,
 * and rendered on every request costs far more than the transfer ever did. So
 * entries are cached post-pipeline and written as a plain PHP array, which
 * opcache holds in memory: a warm request is one `include`, not a parse.
 *
 * The stored metadata does double duty. It carries the HTTP validators that
 * make the next fetch a `304`, and it is the last known good copy a failing
 * source falls back to.
 */
final class SourceCache
{
    use LoggingTrait;

    /**
     * Seconds before a cached source is revalidated, when none is declared.
     */
    private const DEFAULT_TTL = 3600;

    /**
     * @param string|null $directory
     *   Where to store cache files, or NULL to derive one.
     */
    public function __construct(private readonly ?string $directory = null)
    {
    }

    /**
     * Read a source's cached metadata.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     *
     * @return array<string, mixed>
     *   Metadata, or an empty array when nothing is cached.
     */
    public function meta(SourceDefinition $sourceDefinition): array
    {
        $path = $this->path($sourceDefinition, 'json');

        if (!is_file($path)) {
            return [];
        }

        $contents = @file_get_contents($path);

        if ($contents === false) {
            return [];
        }

        $decoded = json_decode($contents, true);

        return is_array($decoded) ? $decoded : [];
    }

    /**
     * Read a source's cached entries.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     *
     * @return array<int, mixed>|null
     *   The entries, or NULL when nothing usable is cached.
     */
    public function entries(SourceDefinition $sourceDefinition): ?array
    {
        $path = $this->path($sourceDefinition, 'php');

        if (!is_file($path)) {
            return null;
        }

        $entries = @include $path;

        return is_array($entries) ? $entries : null;
    }

    /**
     * Whether a cached copy is young enough to use without revalidating.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source, for its declared TTL.
     * @param array<string, mixed> $meta
     *   Metadata from a previous store.
     *
     * @return bool
     *   True when the cache may be used as-is.
     */
    public function isFresh(SourceDefinition $sourceDefinition, array $meta): bool
    {
        $fetchedAt = $meta['fetched_at'] ?? null;

        if (!is_int($fetchedAt)) {
            return false;
        }

        return (time() - $fetchedAt) < $this->ttl($sourceDefinition);
    }

    /**
     * Store a source's entries and metadata.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     * @param array<int, mixed> $entries
     *   Rendered, validated entries.
     * @param array<string, mixed> $meta
     *   Validators and counters to carry forward.
     */
    public function store(SourceDefinition $sourceDefinition, array $entries, array $meta): void
    {
        $directory = $this->directory();

        if (!is_dir($directory) && !@mkdir($directory, 0775, true) && !is_dir($directory)) {
            $this->getLogger()->warning('Unable to create source cache directory', [
                'directory' => $directory,
            ]);

            return;
        }

        $meta['fetched_at'] = time();
        $meta['entry_count'] = count($entries);
        $meta['source'] = $sourceDefinition->name;

        $this->write(
            $this->path($sourceDefinition, 'php'),
            '<?php' . PHP_EOL
            . '// Generated by Kanopi\\Firewall — source "' . $sourceDefinition->name . '". Do not edit.' . PHP_EOL
            . 'return ' . var_export($entries, true) . ';' . PHP_EOL
        );

        $encoded = json_encode($meta, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

        if ($encoded !== false) {
            $this->write($this->path($sourceDefinition, 'json'), $encoded);
        }
    }

    /**
     * Discard a source's cached entries and metadata.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     */
    public function forget(SourceDefinition $sourceDefinition): void
    {
        foreach (['php', 'json'] as $extension) {
            $path = $this->path($sourceDefinition, $extension);

            if (is_file($path)) {
                @unlink($path);
            }
        }
    }

    /**
     * Seconds a cached copy stays usable before revalidation.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     *
     * @return int
     *   The effective TTL.
     */
    public function ttl(SourceDefinition $sourceDefinition): int
    {
        if ($sourceDefinition->ttl !== null) {
            return $sourceDefinition->ttl;
        }

        if (defined('KANOPI_FIREWALL_CACHE_TTL')) {
            return (int) constant('KANOPI_FIREWALL_CACHE_TTL');
        }

        return self::DEFAULT_TTL;
    }

    /**
     * Where cache files are written.
     *
     * Mirrors the other plugin caches so a deployment that already sets
     * KANOPI_FIREWALL_CACHE_DIR does not have to say it twice.
     *
     * @return string
     *   An absolute directory path.
     */
    public function directory(): string
    {
        if (is_string($this->directory) && trim($this->directory) !== '') {
            return rtrim(trim($this->directory), '/');
        }

        if (defined('KANOPI_FIREWALL_CACHE_DIR')) {
            return rtrim((string) constant('KANOPI_FIREWALL_CACHE_DIR'), '/') . '/sources';
        }

        return sys_get_temp_dir() . '/kanopi-firewall-sources';
    }

    /**
     * Path to one of a source's cache files.
     *
     * Keyed on the definition fingerprint, so editing a `select` or `template`
     * invalidates the cache even though the upstream did not change.
     *
     * @param SourceDefinition $sourceDefinition
     *   The source.
     * @param string $extension
     *   File extension, `php` for entries or `json` for metadata.
     *
     * @return string
     *   An absolute file path.
     */
    private function path(SourceDefinition $sourceDefinition, string $extension): string
    {
        return $this->directory() . '/' . substr($sourceDefinition->fingerprint(), 0, 32) . '.' . $extension;
    }

    /**
     * Write a cache file atomically.
     *
     * A partially written entries file would be included verbatim on the next
     * request, so it is staged beside the target and renamed into place.
     *
     * @param string $path
     *   Destination path.
     * @param string $contents
     *   What to write.
     */
    private function write(string $path, string $contents): void
    {
        $temporary = $path . '.' . getmypid() . '.tmp';

        if (@file_put_contents($temporary, $contents, LOCK_EX) === false) {
            $this->getLogger()->warning('Unable to write source cache file', ['file' => $path]);

            return;
        }

        @chmod($temporary, 0644);

        if (!@rename($temporary, $path)) {
            @unlink($temporary);
            $this->getLogger()->warning('Unable to publish source cache file', ['file' => $path]);

            return;
        }

        if (function_exists('opcache_invalidate') && str_ends_with($path, '.php')) {
            @opcache_invalidate($path, true);
        }
    }
}
